# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

objectivefzRcpp <- function(par, T, ab, wt, aj1T, bj1T, cj1T, nummet, itmp, D, base) {
    .Call(`_equateMultiple_objectivefzRcpp`, par, T, ab, wt, aj1T, bj1T, cj1T, nummet, itmp, D, base)
}

hessRcpp <- function(par, T, ab, wt, aj1T, bj1T, cj1T, nummet, itmp, D, base) {
    .Call(`_equateMultiple_hessRcpp`, par, T, ab, wt, aj1T, bj1T, cj1T, nummet, itmp, D, base)
}

gradRcpp <- function(par, T, ab, wt, aj1T, bj1T, cj1T, nummet, itmp, D, base) {
    .Call(`_equateMultiple_gradRcpp`, par, T, ab, wt, aj1T, bj1T, cj1T, nummet, itmp, D, base)
}

partialABgammaRcpp <- function(par, T, ab, wt, aj1T, bj1T, cj1T, nummet, itmp, D, base, nb, posnomi) {
    .Call(`_equateMultiple_partialABgammaRcpp`, par, T, ab, wt, aj1T, bj1T, cj1T, nummet, itmp, D, base, nb, posnomi)
}

ipfRcpp <- function(aj1T, base, eps) {
    .Call(`_equateMultiple_ipfRcpp`, aj1T, base, eps)
}

profLikRcpp <- function(par, coef, t, X_list, itmvar, numforms, notbase, DffcltNum, DscrmnNum, pos) {
    .Call(`_equateMultiple_profLikRcpp`, par, coef, t, X_list, itmvar, numforms, notbase, DffcltNum, DscrmnNum, pos)
}

profLikRcpp_1PL <- function(par, coef, t, X_list, itmvar, numforms, notbase, pos) {
    .Call(`_equateMultiple_profLikRcpp_1PL`, par, coef, t, X_list, itmvar, numforms, notbase, pos)
}

